{% set version = "1.2-9" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-brobdingnag
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Brobdingnag_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Brobdingnag/Brobdingnag_{{ version }}.tar.gz
  sha256: f9012d250bc2a0f47815d6a7c06df2d4ddf3d8bab2d3b75e8cdefd964d20e91e

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrix >=1.5_0
  run:
    - r-base
    - r-matrix >=1.5_0

test:
  commands:
    - $R -e "library('Brobdingnag')"           # [not win]
    - "\"%R%\" -e \"library('Brobdingnag')\""  # [win]

about:
  home: https://github.com/RobinHankin/Brobdingnag.git
  license: GPL-2.0-or-later
  summary: Handles very large numbers in R.  Real numbers are held using their natural logarithms, plus a logical flag indicating sign.  The package includes a vignette that gives a step-by-step introduction to using S4 methods.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
