appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: P89Ibd+EmZqzOidewWGPFsSVmwnJ9EZfTCNwRbnFMNVuPtB4iOfb3vwGHIpYWcelyFcfXXJUk2KiW5HQ+SKWGX49qWb+DuiR7bmhWVg4Fo3c19Qa2m3A2cC6AnoZjFriFqFQZI4jokbOWr9JqWYsIHZT6DF0XTiILV35QzdY9OeORsof22RmpWBv6CYa34UlVwae9vQTjqEKcZC6SqQVU4ZXy7Nc+gysv4SiFmWm9VNTboExXEyBLcBgWbHEv+/GLdM00bsCEn6uXsrTp7oLXGSRfqt4ZB20qObI25hkfoiSUdXQG2eGKboL9t92KF+TGrnKJ/Vrnen0gM87M6aFpTXM6Zjw4GRor+ku5MbqbcBzVcFp/BHoncmIv0ESF11p86lJMFHMmeSSZjrFcOEqVI8l0XIeKTuhhLxjq1jDj9YFdhX8z3CgUPrEFXRIOxLQc5Yv4tqg3UOiTrYDnNBn+zRjzR5pe12n7brvuJRkASjXiVTFbNjvv7DN2z8q/vwowC5bsdPB+XMQk5pPTg+o4HWr9c/VMb6QybluN8aL3vPJnu9aPikqjIrZIj89e9OicQyLt9YqcPjwsVWx3jiXHihdODMRp3ot8DRLOaW1oqun409naIpPh6u726k1uKIZo0F1TWCtOVX+9zIAYVj+/oYmOfgty973GhR72Q1YViM=}
