travis:
  secure:
    BINSTAR_TOKEN: pYdjoZtMJkNtL7+e/OgFDWIH2qXjYaxhfRbn72wJM/ErI8/Wi7Q2MtXkzShqphGQVm+QGo9hVPyIgJ+AYmF3nJ3mdKSTqyrUrXXAmFR0M7693T6FqA9U1ViTiodjUbqsW3Il6kWDSDOIW3YGZyG08ro+T63bMHlRQyGMLlHiL963T4ZjfMTNh989GKVpnesNgIZVvy5xg9U2mzhMg7SuJmjjIzfE5iB+HaGRyO38Lmkl/ligINFhTN4NsFpKwNVjjbgWxRKbO9etJGYWrIw3xc9+ObyxWBCuqD4k8dYOXO76jxwYIyg//avNJKXy3OyhAJJrZ5+CpkFabYEqx5wNz2LYRlWPTW2WnCgabs89visxFtyjfJdTwGesohhcAYsy069ii7js2102vag3hihg/KiSm8pz/s3Yse6Xuf7yllYmKey+4jECiGDXrZSl+Sn0A9JmtxWHfrIBPDHkcdh9xPF8m7g9+UQdbGmMZG+jA2Q6I+4C78ClA9hpBLrCGytrCRiss0N32e6xfxYar8gkkWW2JeW2CpW5eGqOiD1zUFKStUIt88hUpYuyi4AnUR/CIkhvVB2mF+1XqyrUAXYF7W0ZrhtxpLMdoICMM3eSx0ag/xbzZtU+ttZxfvqLoHpGX5/ENIYGvz6zLV7MdMWkQzTMOVwd7n1SByDB/CiihCg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
